#!/bin/bash

set -ex

## Check if juju stable repo is installed, otherwise install
egrep -q '^deb .*juju.*stable.*' /etc/apt/sources.list.d/*.list || \
  (
    sudo add-apt-repository -y ppa:juju/stable && \
    sudo apt-get -y  update
  )

## Check if package is installed, otherwise install
check_install () {
  dpkg -s $1 &> /dev/null || sudo apt -y install $1
}

for PKG in amulet \
           distro-info-data \
           python-cinderclient \
           python-distro-info \
           python-glanceclient \
           python-heatclient \
           python-keystoneclient \
           python-neutronclient \
           python-novaclient \
           python-pika \
           python-swiftclient
    do
        check_install $PKG
    done
